# Generated by Django 3.2.8 on 2021-10-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.userpost'),
        ),
    ]
