# Generated by Django 3.2.8 on 2021-10-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_alter_comment_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='react',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
