# Generated by Django 3.2.8 on 2021-11-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0004_alter_like_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
